### ISSUE TITLE
screenshot link dead

### ISSUE THREAD

**Issue by jyriok** [ankane/pghero.sql#6]
hi,

just for inform u your screenshot link is dead on your first page ;)
https://camo.githubusercontent.com/2e0e5450faeac0d6eca09a0bdd852e0d36f8136e/68747470733a2f2f70676865726f2e6865726f6b756170702e636f6d2f6173736574732f636f6e736f6c652d37356539396334613665303439393433646136656261363662336437353865372e706e67

bye

**Comment by ankane** [comment]
Hey @jyriok, thanks for reporting 👍  Somehow missed this. Fixed now.
